#!/usr/bin/env bash

usage() {

echo "
cf-deploy: Copies files to an S3 bucket and triggers the cloud front distribution to rebuild

USAGE: cf-deploy [OPTIONS]

    OPTIONS
        -b [bucket]         The fully qualified S3 bucket
        -d [distro]         The cloud front distribution id
        -p [path]           The code path to copy to S3

    "
}


if [ "$1" == "" ]; then
usage
exit 0
fi

while getopts ":h:b:d:p:" opts; do
case $opts in
    h)
        usage
        exit 0
        ;;
    b)
        bucket=$OPTARG
        ;;
    p)
        path=$OPTARG
        ;;
    d)
        distro=$OPTARG
        ;;
    \? | :)
        usage
        exit 1
        ;;
  esac
done



deployCloudfront() {



    echo "Copying to S3 bucket ${1}"

    aws s3 cp ${3} s3://${1}/ --recursive --include "*" --acl public-read
    # invalidate the whole distro
    aws configure set preview.cloudfront true
    echo "Invalidating the cloudfront distribution ${2}"
    aws cloudfront create-invalidation --distribution-id ${2} --paths '/*'
}



deployCloudfront ${bucket} ${distro} ${path}